import DS from 'ember-data';

export default DS.Model.extend({
  name: DS.attr('string'),
  // hostgroup: DS.attr('string'),
  // mac: DS.attr('string'),
  // domain: DS.attr('string'),
  // subnet: DS.attr('string'),
  // operatingsystem: DS.attr('string'),
  // environment: DS.attr('string'),
  // model: DS.attr('string'),
  // location: DS.attr('string'),
  // organization: DS.attr('string'),
  // cpu: DS.attr('string'),
  // memory: DS.attr('string'),
  // vendor: DS.attr('string'),

  // isSelectedAsHypervisor: DS.attr('boolean'),
  // isSelectedAsEngine: DS.attr('boolean'),

  ip: DS.attr('string'),
  environment_id: DS.attr('number'),
  environment_name: DS.attr('string'),
  mac: DS.attr('string'),
  // sp_mac: DS.attr('string'),
  // sp_ip: DS.attr('string'),
  // sp_name: DS.attr('string'),
  build: DS.attr('boolean'),

  realm_id: DS.attr('number'),
  realm_name: DS.attr('string'),
  domain_id: DS.attr('number'),
  domain_name: DS.attr('string'),
  architecture_id: DS.attr('number'),
  architecture_name: DS.attr('string'),
  operatingsystem_id: DS.attr('number'),
  operatingsystem_name: DS.attr('string'),
  subnet_id: DS.attr('number'),
  subnet_name: DS.attr('string'),
  ptable_id: DS.attr('number'),
  ptable_name: DS.attr('string'),
  medium_id: DS.attr('number'),
  medium_name: DS.attr('string'),
  model_id: DS.attr('number'),
  model_name2: DS.attr('string'), //doesn't work in HostSerializer model_name2 {serialize: false}
  hostgroup_id: DS.attr('number'),
  hostgroup_name: DS.attr('string'),
  owner_id: DS.attr('number'),
  owner_type: DS.attr('string'),
  compute_resource_id: DS.attr('number'),
  compute_resource_name: DS.attr('string'),
  compute_profile_id: DS.attr('number'),
  compute_profile_name: DS.attr('string'),
  organization_id: DS.attr('number'),
  organization_name: DS.attr('string'),
  location_id: DS.attr('number'),
  location_name: DS.attr('string'),
  image_id: DS.attr('number'),
  image_name: DS.attr('string'),

  managed: DS.attr('boolean'),
  enabled: DS.attr('boolean'),
  puppet_ca_proxy_id: DS.attr('number'),
  puppet_proxy_id: DS.attr('number'),
  sp_subnet_id: DS.attr('number'),

  created_at: DS.attr('date'),
  updated_at: DS.attr('date'),


});

            // "last_report": "2013-05-13T05:25:41Z",
            // "sp_subnet_id": null,
            // "comment": "",
            // "disk": "",
            // "installed_at": "2013-05-05T11:23:32Z",
            // "use_image": null,
            // "image_file": "",
            // "uuid": null,
            // "capabilities": [
            //     "build"
            // ],
            // "provision_method": "build",
            // "": 7,
            // "certname": "183999ca-45f1-411d-a1e5-9e50ccd9e1f5",
            // "created_at": "2013-05-02T07:52:52Z",
            // "updated_at": "2014-03-19T09:04:06Z",
            // "last_compile": "2013-05-13T07:25:40Z",
            // "last_freshcheck": null,
            // "serial": null,
            // "source_file_id": null,
            // "puppet_status": 0,
