import DS from 'ember-data';

export default DS.Model.extend({
  name: DS.attr('string'),
  title: DS.attr('string'),
  ancestry: DS.attr('string'),
  operatingsystem_id: DS.attr('number'),
  operatingsystem_name: DS.attr('string'),
  subnet_id: DS.attr('number'),
  subnet_name: DS.attr('string'),
  domain_id: DS.attr('number'),
  domain_name: DS.attr('string'),
  environment_id: DS.attr('number'),
  environment_name: DS.attr('string'),
  compute_profile_id: DS.attr('number'),
  compute_profile_name: DS.attr('string'),
  puppet_ca_proxy_id: DS.attr('number'),
  puppet_proxy_id: DS.attr('number'),
  architecture_id: DS.attr('number'),
  architecture_name: DS.attr('string'),
  ptable_id: DS.attr('number'),
  ptable_name: DS.attr('string'),
  medium_id: DS.attr('number'),
  medium_name: DS.attr('string'),
  created_at: DS.attr('date'),
  updated_at: DS.attr('date'),
});
